In [2]:
%load_ext autoreload
%autoreload 2


import sys
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import polars as pl

sys.path.append('../')

from data_pipeline import load_all_raw_data

from data_analysis import (
    filter_data_until_date, temporal_split_data, 
)

from plots.data_plot import (
    plot_user_analysis, plot_temporal_analysis, 
    plot_station_analysis, plot_activity_heatmap, 
    print_summary_statistics
)

from preprocess import (
    analyze_users_for_visualization, 
    analyze_trips_for_visualization
)

from weather_data import WeatherDataCollector

In [4]:
trips_with_weather = pd.read_csv('../../data/processed/trips_with_weather.csv')

In [5]:
# Convert trips_with_weather to parquet format for more efficient storage and faster loading
#trips_with_weather.to_parquet('../data/processed/trips_with_weather.parquet', compression='snappy')

In [3]:
trips_with_weather = pd.read_parquet('../data/processed/trips_with_weather.parquet')

AttributeError: Can only use .dt accessor with datetimelike values

In [8]:
trips_with_weather['fecha_origen_recorrido'] = pd.to_datetime(trips_with_weather['fecha_origen_recorrido'])
trips_with_weather = trips_with_weather[trips_with_weather['fecha_origen_recorrido'].dt.year >= 2023]

In [12]:
trips_with_weather.isna().sum()

id_recorrido                                 0
duracion_recorrido                           0
fecha_origen_recorrido                       0
id_estacion_origen                           0
nombre_estacion_origen                       0
direccion_estacion_origen                    0
long_estacion_origen                         0
lat_estacion_origen                          0
fecha_destino_recorrido                      0
id_estacion_destino                          2
nombre_estacion_destino                      2
direccion_estacion_destino                   2
long_estacion_destino                        2
lat_estacion_destino                         2
id_usuario                                   0
modelo_bicicleta                             0
genero                                   19625
weather_temperature_2m                       0
weather_relative_humidity_2m                 0
weather_dew_point_2m                         0
weather_apparent_temperature                 0
weather_precipitation                        0
weather_rain                                 0
weather_weather_code                         0
weather_pressure_msl                         0
weather_surface_pressure                     0
weather_cloud_cover                          0
weather_cloud_cover_low                      0
weather_cloud_cover_mid                      0
weather_cloud_cover_high                     0
weather_et0_fao_evapotranspiration           0
weather_vapour_pressure_deficit              0
weather_wind_speed_10m                       0
weather_wind_speed_100m                      0
weather_wind_direction_10m                   0
weather_wind_direction_100m                  0
weather_wind_gusts_10m                       0
weather_soil_temperature_0_to_7cm            0
weather_soil_temperature_7_to_28cm           0
weather_soil_temperature_28_to_100cm         0
weather_soil_temperature_100_to_255cm        0
weather_soil_moisture_0_to_7cm               0
weather_soil_moisture_7_to_28cm              0
weather_soil_moisture_28_to_100cm            0
weather_soil_moisture_100_to_255cm           0
weather_sunshine_duration                    0
weather_is_day                               0
weather_direct_radiation                     0
dtype: int64

In [16]:
from data_analysis import engineer_ecobici_features

df_feat = engineer_ecobici_features(trips_with_weather)

df_feat.describe()

🚴‍♂️  Parametrized Feature Engineering Pipeline (11 steps)
============================================================
  Checkpoints directory: 'feature_checkpoints/'
  Input raw data shape: (4777560, 48)
  -> Memory usage after initialization: 4756.4 MB
[Step 1/11] Converting to Polars and normalizing dates...

  -> Saved Polars conversion checkpoint: step01_polars_conversion.parquet
[Step 2/11] Creating departures table with lags & user profiles...

  -> Saved departures table checkpoint: step02_departures.parquet
[Step 3/11] Creating arrivals table with lags...

  -> Saved arrivals table checkpoint: step03_arrivals.parquet
[Step 4/11] Creating shifted arrivals table for target...

  -> Saved shifted arrivals checkpoint: step04_shifted_arrivals.parquet
[Step 5/11] Creating enhanced weather table...

  -> Saved weather table checkpoint: step05_weather.parquet
[Step 6/11] Creating station metadata table...

  -> Saved station metadata checkpoint: step06_stations.parquet
[Step 7/11] Building full station x time skeleton...

  -> Saved skeleton checkpoint: step07_skeleton.parquet
  -> Memory usage after after clearing main dataframe: 7238.4 MB
[Step 8/11] Joining data onto skeleton...

  -> Saved joined features checkpoint: step08_joined_with_weather.parquet
[Step 9/11] Engineering temporal and calendar features...
  -> Creating temporal features with memory optimization...
  -> Processing window: 2023-01-01 00:00:00 to 2023-01-08 00:00:00
  -> Memory usage after processed window until 2023-01-08 00:00:00: 6273.4 MB
  -> Processing window: 2023-01-08 00:00:00 to 2023-01-15 00:00:00
  -> Memory usage after processed window until 2023-01-15 00:00:00: 2327.1 MB
  -> Processing window: 2023-01-15 00:00:00 to 2023-01-22 00:00:00
  -> Memory usage after processed window until 2023-01-22 00:00:00: 275.8 MB
  -> Processing window: 2023-01-22 00:00:00 to 2023-01-29 00:00:00
  -> Memory usage after processed window until 2023-01-29 00:00:00: 126.7 MB
  -> Processing window: 2023-01-29 00:00:00 to 2023-02-05 00:00:00
  -> Memory usage after processed window until 2023-02-05 00:00:00: 92.5 MB
  -> Processing window: 2023-02-05 00:00:00 to 2023-02-12 00:00:00
  -> Memory usage after processed window until 2023-02-12 00:00:00: 238.4 MB
  -> Processing window: 2023-02-12 00:00:00 to 2023-02-19 00:00:00
  -> Memory usage after processed window until 2023-02-19 00:00:00: 211.9 MB
  -> Processing window: 2023-02-19 00:00:00 to 2023-02-26 00:00:00
  -> Memory usage after processed window until 2023-02-26 00:00:00: 198.2 MB
  -> Processing window: 2023-02-26 00:00:00 to 2023-03-05 00:00:00
  -> Memory usage after processed window until 2023-03-05 00:00:00: 122.9 MB
  -> Processing window: 2023-03-05 00:00:00 to 2023-03-12 00:00:00
  -> Memory usage after processed window until 2023-03-12 00:00:00: 195.3 MB
  -> Processing window: 2023-03-12 00:00:00 to 2023-03-19 00:00:00
  -> Memory usage after processed window until 2023-03-19 00:00:00: 172.3 MB
  -> Processing window: 2023-03-19 00:00:00 to 2023-03-26 00:00:00
  -> Memory usage after processed window until 2023-03-26 00:00:00: 473.5 MB
  -> Processing window: 2023-03-26 00:00:00 to 2023-04-02 00:00:00
  -> Memory usage after processed window until 2023-04-02 00:00:00: 693.5 MB
  -> Processing window: 2023-04-02 00:00:00 to 2023-04-09 00:00:00
  -> Memory usage after processed window until 2023-04-09 00:00:00: 743.5 MB
  -> Processing window: 2023-04-09 00:00:00 to 2023-04-16 00:00:00
  -> Memory usage after processed window until 2023-04-16 00:00:00: 811.5 MB
  -> Processing window: 2023-04-16 00:00:00 to 2023-04-23 00:00:00
  -> Memory usage after processed window until 2023-04-23 00:00:00: 859.5 MB
  -> Processing window: 2023-04-23 00:00:00 to 2023-04-30 00:00:00
  -> Memory usage after processed window until 2023-04-30 00:00:00: 912.3 MB
  -> Processing window: 2023-04-30 00:00:00 to 2023-05-07 00:00:00
  -> Memory usage after processed window until 2023-05-07 00:00:00: 971.3 MB
  -> Processing window: 2023-05-07 00:00:00 to 2023-05-14 00:00:00
  -> Memory usage after processed window until 2023-05-14 00:00:00: 1006.2 MB
  -> Processing window: 2023-05-14 00:00:00 to 2023-05-21 00:00:00
  -> Memory usage after processed window until 2023-05-21 00:00:00: 1050.5 MB
  -> Processing window: 2023-05-21 00:00:00 to 2023-05-28 00:00:00
  -> Memory usage after processed window until 2023-05-28 00:00:00: 1102.2 MB
  -> Processing window: 2023-05-28 00:00:00 to 2023-06-04 00:00:00
  -> Memory usage after processed window until 2023-06-04 00:00:00: 1142.3 MB
  -> Processing window: 2023-06-04 00:00:00 to 2023-06-11 00:00:00
  -> Memory usage after processed window until 2023-06-11 00:00:00: 1204.3 MB
  -> Processing window: 2023-06-11 00:00:00 to 2023-06-18 00:00:00
  -> Memory usage after processed window until 2023-06-18 00:00:00: 1260.5 MB
  -> Processing window: 2023-06-18 00:00:00 to 2023-06-25 00:00:00
  -> Memory usage after processed window until 2023-06-25 00:00:00: 1300.1 MB
  -> Processing window: 2023-06-25 00:00:00 to 2023-07-02 00:00:00
  -> Memory usage after processed window until 2023-07-02 00:00:00: 1336.8 MB
  -> Processing window: 2023-07-02 00:00:00 to 2023-07-09 00:00:00
  -> Memory usage after processed window until 2023-07-09 00:00:00: 1399.4 MB
  -> Processing window: 2023-07-09 00:00:00 to 2023-07-16 00:00:00
  -> Memory usage after processed window until 2023-07-16 00:00:00: 1444.7 MB
  -> Processing window: 2023-07-16 00:00:00 to 2023-07-23 00:00:00
  -> Memory usage after processed window until 2023-07-23 00:00:00: 1501.4 MB
  -> Processing window: 2023-07-23 00:00:00 to 2023-07-30 00:00:00
  -> Memory usage after processed window until 2023-07-30 00:00:00: 1545.1 MB
  -> Processing window: 2023-07-30 00:00:00 to 2023-08-06 00:00:00
  -> Memory usage after processed window until 2023-08-06 00:00:00: 1593.2 MB
  -> Processing window: 2023-08-06 00:00:00 to 2023-08-13 00:00:00
  -> Memory usage after processed window until 2023-08-13 00:00:00: 1657.4 MB
  -> Processing window: 2023-08-13 00:00:00 to 2023-08-20 00:00:00
  -> Memory usage after processed window until 2023-08-20 00:00:00: 1703.5 MB
  -> Processing window: 2023-08-20 00:00:00 to 2023-08-27 00:00:00
  -> Memory usage after processed window until 2023-08-27 00:00:00: 1740.3 MB
  -> Processing window: 2023-08-27 00:00:00 to 2023-09-03 00:00:00
  -> Memory usage after processed window until 2023-09-03 00:00:00: 1811.7 MB
  -> Processing window: 2023-09-03 00:00:00 to 2023-09-10 00:00:00
  -> Memory usage after processed window until 2023-09-10 00:00:00: 1867.3 MB
  -> Processing window: 2023-09-10 00:00:00 to 2023-09-17 00:00:00
  -> Memory usage after processed window until 2023-09-17 00:00:00: 1898.0 MB
  -> Processing window: 2023-09-17 00:00:00 to 2023-09-24 00:00:00
  -> Memory usage after processed window until 2023-09-24 00:00:00: 1955.4 MB
  -> Processing window: 2023-09-24 00:00:00 to 2023-10-01 00:00:00
  -> Memory usage after processed window until 2023-10-01 00:00:00: 1990.6 MB
  -> Processing window: 2023-10-01 00:00:00 to 2023-10-08 00:00:00
  -> Memory usage after processed window until 2023-10-08 00:00:00: 2040.6 MB
  -> Processing window: 2023-10-08 00:00:00 to 2023-10-15 00:00:00
  -> Memory usage after processed window until 2023-10-15 00:00:00: 2105.2 MB
  -> Processing window: 2023-10-15 00:00:00 to 2023-10-22 00:00:00
  -> Memory usage after processed window until 2023-10-22 00:00:00: 2150.9 MB
  -> Processing window: 2023-10-22 00:00:00 to 2023-10-29 00:00:00
  -> Memory usage after processed window until 2023-10-29 00:00:00: 2185.8 MB
  -> Processing window: 2023-10-29 00:00:00 to 2023-11-05 00:00:00
  -> Memory usage after processed window until 2023-11-05 00:00:00: 2244.9 MB
  -> Processing window: 2023-11-05 00:00:00 to 2023-11-12 00:00:00
  -> Memory usage after processed window until 2023-11-12 00:00:00: 2302.4 MB
  -> Processing window: 2023-11-12 00:00:00 to 2023-11-19 00:00:00
  -> Memory usage after processed window until 2023-11-19 00:00:00: 2345.2 MB
  -> Processing window: 2023-11-19 00:00:00 to 2023-11-26 00:00:00
  -> Memory usage after processed window until 2023-11-26 00:00:00: 2392.9 MB
  -> Processing window: 2023-11-26 00:00:00 to 2023-12-03 00:00:00
  -> Memory usage after processed window until 2023-12-03 00:00:00: 2433.7 MB
  -> Processing window: 2023-12-03 00:00:00 to 2023-12-10 00:00:00
  -> Memory usage after processed window until 2023-12-10 00:00:00: 2483.4 MB
  -> Processing window: 2023-12-10 00:00:00 to 2023-12-17 00:00:00
  -> Memory usage after processed window until 2023-12-17 00:00:00: 2556.6 MB
  -> Processing window: 2023-12-17 00:00:00 to 2023-12-24 00:00:00
  -> Memory usage after processed window until 2023-12-24 00:00:00: 2590.3 MB
  -> Processing window: 2023-12-24 00:00:00 to 2023-12-31 00:00:00
  -> Memory usage after processed window until 2023-12-31 00:00:00: 2636.5 MB
  -> Processing window: 2023-12-31 00:00:00 to 2024-01-07 00:00:00
  -> Memory usage after processed window until 2024-01-07 00:00:00: 2698.7 MB
  -> Processing window: 2024-01-07 00:00:00 to 2024-01-14 00:00:00
  -> Memory usage after processed window until 2024-01-14 00:00:00: 2747.8 MB
  -> Processing window: 2024-01-14 00:00:00 to 2024-01-21 00:00:00
  -> Memory usage after processed window until 2024-01-21 00:00:00: 2790.6 MB
  -> Processing window: 2024-01-21 00:00:00 to 2024-01-28 00:00:00
  -> Memory usage after processed window until 2024-01-28 00:00:00: 2856.7 MB
  -> Processing window: 2024-01-28 00:00:00 to 2024-02-04 00:00:00
  -> Memory usage after processed window until 2024-02-04 00:00:00: 2894.6 MB
  -> Processing window: 2024-02-04 00:00:00 to 2024-02-11 00:00:00
  -> Memory usage after processed window until 2024-02-11 00:00:00: 2952.8 MB
  -> Processing window: 2024-02-11 00:00:00 to 2024-02-18 00:00:00
  -> Memory usage after processed window until 2024-02-18 00:00:00: 3000.3 MB
  -> Processing window: 2024-02-18 00:00:00 to 2024-02-25 00:00:00
  -> Memory usage after processed window until 2024-02-25 00:00:00: 3036.9 MB
  -> Processing window: 2024-02-25 00:00:00 to 2024-03-03 00:00:00
  -> Memory usage after processed window until 2024-03-03 00:00:00: 3085.1 MB
  -> Processing window: 2024-03-03 00:00:00 to 2024-03-10 00:00:00
  -> Memory usage after processed window until 2024-03-10 00:00:00: 3132.6 MB
  -> Processing window: 2024-03-10 00:00:00 to 2024-03-17 00:00:00
  -> Memory usage after processed window until 2024-03-17 00:00:00: 3187.9 MB
  -> Processing window: 2024-03-17 00:00:00 to 2024-03-24 00:00:00
  -> Memory usage after processed window until 2024-03-24 00:00:00: 3250.4 MB
  -> Processing window: 2024-03-24 00:00:00 to 2024-03-31 00:00:00
  -> Memory usage after processed window until 2024-03-31 00:00:00: 3293.3 MB
  -> Processing window: 2024-03-31 00:00:00 to 2024-04-07 00:00:00
  -> Memory usage after processed window until 2024-04-07 00:00:00: 3338.7 MB
  -> Processing window: 2024-04-07 00:00:00 to 2024-04-14 00:00:00
  -> Memory usage after processed window until 2024-04-14 00:00:00: 3385.3 MB
  -> Processing window: 2024-04-14 00:00:00 to 2024-04-21 00:00:00
  -> Memory usage after processed window until 2024-04-21 00:00:00: 3438.6 MB
  -> Processing window: 2024-04-21 00:00:00 to 2024-04-28 00:00:00
  -> Memory usage after processed window until 2024-04-28 00:00:00: 3480.0 MB
  -> Processing window: 2024-04-28 00:00:00 to 2024-05-05 00:00:00
  -> Memory usage after processed window until 2024-05-05 00:00:00: 3563.2 MB
  -> Processing window: 2024-05-05 00:00:00 to 2024-05-12 00:00:00
  -> Memory usage after processed window until 2024-05-12 00:00:00: 3606.8 MB
  -> Processing window: 2024-05-12 00:00:00 to 2024-05-19 00:00:00
  -> Memory usage after processed window until 2024-05-19 00:00:00: 3657.6 MB
  -> Processing window: 2024-05-19 00:00:00 to 2024-05-26 00:00:00
  -> Memory usage after processed window until 2024-05-26 00:00:00: 3695.9 MB
  -> Processing window: 2024-05-26 00:00:00 to 2024-06-02 00:00:00
  -> Memory usage after processed window until 2024-06-02 00:00:00: 3744.7 MB
  -> Processing window: 2024-06-02 00:00:00 to 2024-06-09 00:00:00
  -> Memory usage after processed window until 2024-06-09 00:00:00: 3784.5 MB
  -> Processing window: 2024-06-09 00:00:00 to 2024-06-16 00:00:00
  -> Memory usage after processed window until 2024-06-16 00:00:00: 3848.8 MB
  -> Processing window: 2024-06-16 00:00:00 to 2024-06-23 00:00:00
  -> Memory usage after processed window until 2024-06-23 00:00:00: 3893.3 MB
  -> Processing window: 2024-06-23 00:00:00 to 2024-06-30 00:00:00
  -> Memory usage after processed window until 2024-06-30 00:00:00: 3922.8 MB
  -> Processing window: 2024-06-30 00:00:00 to 2024-07-07 00:00:00
  -> Memory usage after processed window until 2024-07-07 00:00:00: 3976.0 MB
  -> Processing window: 2024-07-07 00:00:00 to 2024-07-14 00:00:00
  -> Memory usage after processed window until 2024-07-14 00:00:00: 4018.7 MB
  -> Processing window: 2024-07-14 00:00:00 to 2024-07-21 00:00:00
  -> Memory usage after processed window until 2024-07-21 00:00:00: 4074.6 MB
  -> Processing window: 2024-07-21 00:00:00 to 2024-07-28 00:00:00
  -> Memory usage after processed window until 2024-07-28 00:00:00: 4120.1 MB
  -> Processing window: 2024-07-28 00:00:00 to 2024-08-04 00:00:00
  -> Memory usage after processed window until 2024-08-04 00:00:00: 4173.8 MB
  -> Processing window: 2024-08-04 00:00:00 to 2024-08-11 00:00:00
  -> Memory usage after processed window until 2024-08-11 00:00:00: 4222.2 MB
  -> Processing window: 2024-08-11 00:00:00 to 2024-08-18 00:00:00
  -> Memory usage after processed window until 2024-08-18 00:00:00: 4279.0 MB
  -> Processing window: 2024-08-18 00:00:00 to 2024-08-25 00:00:00
  -> Memory usage after processed window until 2024-08-25 00:00:00: 4318.8 MB
  -> Processing window: 2024-08-25 00:00:00 to 2024-08-31 00:00:00
  -> Memory usage after processed window until 2024-08-31 00:00:00: 4368.0 MB
  -> Combining all temporal windows...
  -> Cleaning up temporary files...
  -> Final sort by timestamp...
  -> Saving checkpoint: feature_checkpoints\step09_temporal.parquet
[Step 10/11] Engineering expanded demand history features…
  -> Computing window size...
  -> Getting unique stations...
  -> Processing 381 stations one at a time

Processing stations:   3%|▎         | 10/381 [01:54<1:09:13, 11.20s/it]

  -> Memory usage after processed 10/381 stations: 6356.3 MB

Processing stations:   5%|▌         | 20/381 [03:43<1:05:29, 10.88s/it]

  -> Memory usage after processed 20/381 stations: 6358.2 MB

Processing stations:   8%|▊         | 30/381 [05:34<1:04:34, 11.04s/it]

  -> Memory usage after processed 30/381 stations: 6357.3 MB

Processing stations:  10%|█         | 40/381 [07:24<1:02:48, 11.05s/it]

  -> Memory usage after processed 40/381 stations: 6357.8 MB

Processing stations:  13%|█▎        | 50/381 [09:13<59:50, 10.85s/it]

  -> Memory usage after processed 50/381 stations: 6356.6 MB

Processing stations:  16%|█▌        | 60/381 [11:03<58:55, 11.02s/it]

  -> Memory usage after processed 60/381 stations: 6355.9 MB

Processing stations:  18%|█▊        | 70/381 [12:53<56:20, 10.87s/it]

  -> Memory usage after processed 70/381 stations: 6355.3 MB

Processing stations:  21%|██        | 80/381 [14:40<53:49, 10.73s/it]

  -> Memory usage after processed 80/381 stations: 6357.3 MB

Processing stations:  24%|██▎       | 90/381 [16:29<52:13, 10.77s/it]

  -> Memory usage after processed 90/381 stations: 6358.8 MB

Processing stations:  26%|██▌       | 100/381 [18:18<51:08, 10.92s/it]

  -> Memory usage after processed 100/381 stations: 6355.2 MB

Processing stations:  29%|██▉       | 110/381 [20:07<49:13, 10.90s/it]

  -> Memory usage after processed 110/381 stations: 6355.8 MB

Processing stations:  31%|███▏      | 120/381 [21:57<48:17, 11.10s/it]

  -> Memory usage after processed 120/381 stations: 6355.9 MB

Processing stations:  34%|███▍      | 130/381 [23:46<45:05, 10.78s/it]

  -> Memory usage after processed 130/381 stations: 6356.2 MB

Processing stations:  37%|███▋      | 140/381 [25:35<43:44, 10.89s/it]

  -> Memory usage after processed 140/381 stations: 6354.9 MB

Processing stations:  39%|███▉      | 150/381 [27:25<42:06, 10.94s/it]

  -> Memory usage after processed 150/381 stations: 5307.6 MB

Processing stations:  42%|████▏     | 160/381 [29:14<39:28, 10.72s/it]

  -> Memory usage after processed 160/381 stations: 5308.8 MB

Processing stations:  45%|████▍     | 170/381 [31:03<38:08, 10.84s/it]

  -> Memory usage after processed 170/381 stations: 5310.0 MB

Processing stations:  47%|████▋     | 180/381 [32:51<35:51, 10.70s/it]

  -> Memory usage after processed 180/381 stations: 5308.6 MB

Processing stations:  50%|████▉     | 190/381 [34:39<34:34, 10.86s/it]

  -> Memory usage after processed 190/381 stations: 5308.7 MB

Processing stations:  52%|█████▏    | 200/381 [36:28<32:42, 10.84s/it]

  -> Memory usage after processed 200/381 stations: 5310.7 MB

Processing stations:  55%|█████▌    | 210/381 [38:18<31:07, 10.92s/it]

  -> Memory usage after processed 210/381 stations: 5313.4 MB

Processing stations:  58%|█████▊    | 220/381 [40:09<30:16, 11.28s/it]

  -> Memory usage after processed 220/381 stations: 5308.6 MB

Processing stations:  60%|██████    | 230/381 [42:00<28:14, 11.22s/it]

  -> Memory usage after processed 230/381 stations: 5308.7 MB

Processing stations:  63%|██████▎   | 240/381 [43:48<25:21, 10.79s/it]

  -> Memory usage after processed 240/381 stations: 5310.2 MB

Processing stations:  66%|██████▌   | 250/381 [45:37<23:49, 10.91s/it]

  -> Memory usage after processed 250/381 stations: 5310.1 MB

Processing stations:  68%|██████▊   | 260/381 [47:27<22:09, 10.98s/it]

  -> Memory usage after processed 260/381 stations: 5153.7 MB

Processing stations:  71%|███████   | 270/381 [49:15<19:59, 10.80s/it]

  -> Memory usage after processed 270/381 stations: 5153.1 MB

Processing stations:  73%|███████▎  | 280/381 [51:05<18:42, 11.11s/it]

  -> Memory usage after processed 280/381 stations: 5152.2 MB

Processing stations:  76%|███████▌  | 290/381 [52:56<17:07, 11.29s/it]

  -> Memory usage after processed 290/381 stations: 4479.2 MB

Processing stations:  79%|███████▊  | 300/381 [54:50<15:48, 11.72s/it]

  -> Memory usage after processed 300/381 stations: 5153.7 MB

Processing stations:  81%|████████▏ | 310/381 [56:39<13:09, 11.13s/it]

  -> Memory usage after processed 310/381 stations: 5115.6 MB

Processing stations:  84%|████████▍ | 320/381 [58:30<11:14, 11.05s/it]

  -> Memory usage after processed 320/381 stations: 5114.9 MB

Processing stations:  87%|████████▋ | 330/381 [1:00:21<09:25, 11.10s/it]

  -> Memory usage after processed 330/381 stations: 5112.2 MB

Processing stations:  89%|████████▉ | 340/381 [1:02:11<07:31, 11.00s/it]

  -> Memory usage after processed 340/381 stations: 5097.2 MB

Processing stations:  92%|█████████▏| 350/381 [1:04:01<05:41, 11.02s/it]

  -> Memory usage after processed 350/381 stations: 5096.5 MB

Processing stations:  94%|█████████▍| 360/381 [1:05:50<03:48, 10.90s/it]

  -> Memory usage after processed 360/381 stations: 5099.5 MB

Processing stations:  97%|█████████▋| 370/381 [1:07:41<02:00, 10.97s/it]

  -> Memory usage after processed 370/381 stations: 5105.1 MB

Processing stations: 100%|█████████▉| 380/381 [1:09:31<00:11, 11.05s/it]

  -> Memory usage after processed 380/381 stations: 5107.1 MB

  -> Combining all station chunks...
  -> Cleaning up temporary files...
  -> Final sort by timestamp...
  -> Saving checkpoint...
[Step 11/11] Calculating neighbor demand and final cleanup...
  -> Memory usage after step 11 start: 8114.9 MB

Computing neighbors:  20%|██        | 1/5 [00:00<00:00,  4.83it/s]

  -> Memory usage after after coordinates join: 8503.5 MB

Calculating neighbor demand:  40%|████      | 2/5 [00:01<00:02,  1.01it/s]

  -> Memory usage after after neighbor computation: 8516.2 MB

Adding lag features:  60%|██████    | 3/5 [00:14<00:10,  5.28s/it]

  -> Memory usage after after neighbor demand calculation: 6243.2 MB

Final cleanup:  80%|████████  | 4/5 [00:15<00:04,  4.44s/it]

  -> Memory usage after after lag features: 6208.0 MB

  -> Memory usage after after final cleanup: 10272.5 MB
  -> Saved final features checkpoint: step11_final.parquet
  -> Memory usage after step 11 complete: 10887.9 MB
  ✅ Saved final result: feature_checkpoints\df_feat_final_result.parquet

,station_id,ts_start,dep_last_DT,trip_dur_mean_last_DT,model_FIT_cnt,model_ICONIC_cnt,share_male,share_female,share_other,dep_lag_1,...,cos_month,is_weekend,payday_flag,vacation_season,peak_commute,dep_ma_24h,dep_std_24h,dep_ratio_DT_24h,near_dep_sum_DT,near_dep_lag_1
count,11118723.0,11118723,11118723.0,2669829.0,11118723.0,11118723.0,2669829.0,2669829.0,2669829.0,11118723.0,...,11118723.0,11118723.0,11118723.0,11118723.0,11118723.0,11118723.0,11118723.0,11118723.0,11118723.0,11118723.0
mean,288.230971,2023-10-31 23:29:59.999999,0.429684,1342.869213,0.291422,0.138262,0.614462,0.297859,0.083488,0.429644,...,-0.120403,0.284515,0.065792,0.203954,0.178871,1.341704,0.684936,0.15173,2.148099,2.148091
min,2.0,2023-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,144.0,2023-06-01 23:30:00,0.0,606.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.866025,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
50%,273.0,2023-10-31 23:30:00,0.0,940.0,0.0,0.0,0.75,0.0,0.0,0.0,...,-0.5,0.0,0.0,0.0,0.0,1.384615,0.617213,0.0,1.0,1.0
75%,453.0,2024-03-31 23:30:00,0.0,1431.0,0.0,0.0,1.0,0.5,0.0,0.0,...,0.5,1.0,0.0,0.0,0.0,1.761905,1.032796,0.0,3.0,3.0
max,556.0,2024-08-30 23:00:00,31.0,3243356.0,27.0,22.0,1.0,1.0,1.0,31.0,...,1.0,1.0,1.0,1.0,1.0,25.0,17.67767,6.666667,64.0,64.0
std,169.68237,NaN,1.000371,10505.095625,0.758124,0.453819,0.423323,0.396641,0.242073,1.00036,...,0.698261,0.451183,0.247918,0.402935,0.383244,0.786069,0.65635,0.327373,3.083676,3.08368

In [9]:
df_feat = pl.read_parquet(r"C:\Users\xxx\Documents\GitHub\EcoBici-AI\notebooks\feature_checkpoints\df_feat_final_result.parquet")

In [4]:
df_feat.columns

['station_id',
 'ts_start',
 'dep_last_DT',
 'trip_dur_mean_last_DT',
 'model_FIT_cnt',
 'model_ICONIC_cnt',
 'share_male',
 'share_female',
 'share_other',
 'dep_lag_1',
 'dep_lag_2',
 'dep_lag_3',
 'dep_lag_4',
 'dep_lag_5',
 'dep_lag_6',
 'arr_last_DT',
 'arr_lag_1',
 'arr_lag_2',
 'arr_lag_3',
 'arr_lag_4',
 'arr_lag_5',
 'arr_lag_6',
 'y_arrivals_next_DT',
 'weather_temperature_2m',
 'weather_relative_humidity_2m',
 'weather_dew_point_2m',
 'weather_apparent_temperature',
 'weather_precipitation',
 'weather_rain',
 'weather_weather_code',
 'weather_pressure_msl',
 'weather_surface_pressure',
 'weather_cloud_cover',
 'weather_cloud_cover_low',
 'weather_cloud_cover_mid',
 'weather_cloud_cover_high',
 'weather_et0_fao_evapotranspiration',
 'weather_vapour_pressure_deficit',
 'weather_wind_speed_10m',
 'weather_wind_speed_100m',
 'weather_wind_direction_10m',
 'weather_wind_direction_100m',
 'weather_wind_gusts_10m',
 'weather_soil_temperature_0_to_7cm',
 'weather_soil_temperature_7_to_28cm',
 'weather_soil_temperature_28_to_100cm',
 'weather_soil_temperature_100_to_255cm',
 'weather_soil_moisture_0_to_7cm',
 'weather_soil_moisture_7_to_28cm',
 'weather_soil_moisture_28_to_100cm',
 'weather_soil_moisture_100_to_255cm',
 'weather_sunshine_duration',
 'weather_is_day',
 'weather_direct_radiation',
 'precip_flag',
 'wind_dir_sin',
 'wind_dir_cos',
 'weather_code_cat_Clear',
 'weather_code_cat_Clouds',
 'weather_code_cat_Drizzle',
 'weather_code_cat_Rain',
 'weather_code_cat_null',
 'precipitation_lag_1h',
 'rain_lag_1h',
 'is_holiday_ar',
 'sin_hour',
 'cos_hour',
 'sin_dow',
 'cos_dow',
 'sin_month',
 'cos_month',
 'is_weekend',
 'payday_flag',
 'vacation_season',
 'peak_commute',
 'dep_ma_24h',
 'dep_std_24h',
 'dep_ratio_DT_24h',
 'near_dep_sum_DT',
 'near_dep_lag_1']

In [5]:
df_feat.shape

(11118723, 80)

In [10]:
code_cols = ["ts_start"]

feat_cols = ['station_id', 'dep_last_DT', 'trip_dur_mean_last_DT',
       'model_FIT_cnt', 'model_ICONIC_cnt', 'share_male', 'share_female',
       'share_other', 'dep_lag_1', 'dep_lag_2', 'dep_lag_3', 'dep_lag_4',
       'dep_lag_5', 'dep_lag_6', 'arr_last_DT', 'arr_lag_1', 'arr_lag_2',
       'arr_lag_3', 'arr_lag_4', 'arr_lag_5', 'arr_lag_6', 'weather_temperature_2m',
       'weather_relative_humidity_2m', 'weather_dew_point_2m',
       'weather_apparent_temperature', 'weather_precipitation', 'weather_rain',
       'weather_pressure_msl', 'weather_surface_pressure', 'weather_cloud_cover',
       'weather_cloud_cover_low', 'weather_cloud_cover_mid',
       'weather_cloud_cover_high', 'weather_et0_fao_evapotranspiration',
       'weather_vapour_pressure_deficit',
       'weather_soil_temperature_0_to_7cm',
       'weather_soil_moisture_0_to_7cm', 'weather_sunshine_duration',
       'weather_is_day', 'weather_direct_radiation', 'precip_flag',
       'wind_dir_sin', 'wind_dir_cos', 'weather_code_cat_Clear',
       'weather_code_cat_Clouds', 'weather_code_cat_Drizzle',
       'weather_code_cat_Rain', 'weather_code_cat_null',
       'precipitation_lag_1h', 'rain_lag_1h', 'is_holiday_ar', 'sin_hour',
       'cos_hour', 'sin_dow', 'cos_dow', 'sin_month', 'cos_month',
       'is_weekend', 'payday_flag', 'vacation_season', 'peak_commute',
       'dep_ma_24h', 'dep_std_24h', 'dep_ratio_DT_24h', 'near_dep_sum_DT',
       'near_dep_lag_1']

target_col = 'y_arrivals_next_DT'

In [11]:
df_feat = df_feat[code_cols + feat_cols + [target_col]]

QUEDA DROPPEAR ALGUNAS COLUMNAS INNECESARIAS DE WEATHER Y ESTAMOS!

In [15]:
df_feat.sample(5)

shape: (5, 68)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ts_start  ┆ station_i ┆ dep_last_ ┆ trip_dur_ ┆ … ┆ dep_ratio ┆ near_dep_ ┆ near_dep_ ┆ y_arriva │
│ ---       ┆ d         ┆ DT        ┆ mean_last ┆   ┆ _DT_24h   ┆ sum_DT    ┆ lag_1     ┆ ls_next_ │
│ datetime[ ┆ ---       ┆ ---       ┆ _DT       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ DT       │
│ μs]       ┆ i64       ┆ u32       ┆ ---       ┆   ┆ f32       ┆ u32       ┆ u32       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2023-10-0 ┆ 508       ┆ 4         ┆ 3270.5    ┆ … ┆ 1.454545  ┆ 0         ┆ 3         ┆ 2        │
│ 7         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 17:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 333       ┆ 1         ┆ 733.0     ┆ … ┆ 0.5       ┆ 0         ┆ 2         ┆ 0        │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 08:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-02-0 ┆ 254       ┆ 0         ┆ null      ┆ … ┆ 0.0       ┆ 1         ┆ 1         ┆ 0        │
│ 8         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 02:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-10-0 ┆ 49        ┆ 0         ┆ null      ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ 8         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-08-1 ┆ 60        ┆ 0         ┆ null      ┆ … ┆ 0.0       ┆ 3         ┆ 6         ┆ 0        │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 19:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
"ts_start" in df_feat.columns

True

In [16]:
from data_analysis import pivot_features_for_global_model

df_feat_pivot = pivot_features_for_global_model(df_feat)

🔄 Pivoting data to wide format for global model...

[Step 1/3] Identifying columns...
  -> Identified 25 station-specific and 40 global features.

[Step 2/3] Constructing feature (X) matrix...
  -> Loading station-specific features from checkpoint: feature_checkpoints\X_station_wide.parquet
  -> Extracting global features...
  -> Joining global and station-specific features...
  -> Saving final features matrix: feature_checkpoints\X_wide.parquet

[Step 3/3] Constructing target (y) matrix...
  -> Pivoting target variable...
  -> Saving checkpoint: feature_checkpoints\y_wide_unaligned.parquet
  -> Aligning target matrix with feature matrix timestamps...
  -> Saving final target matrix: feature_checkpoints\y_wide.parquet
--------------------------------------------------
  Original long shape: (11118723, 68)
  Pivoted X_wide shape: (29183, 9566) -> saved to X_wide.parquet
  Pivoted y_wide shape: (29183, 382) -> saved to y_wide.parquet
✅ Pivoting complete.

In [14]:
X_wide = pl.read_parquet(r"C:\Users\xxx\Documents\GitHub\EcoBici-AI\notebooks\feature_checkpoints\X_wide.parquet")

In [20]:
X_wide.shape

(29183, 9566)

In [19]:
X_wide.columns

['ts_start',
 'weather_temperature_2m',
 'weather_relative_humidity_2m',
 'weather_dew_point_2m',
 'weather_apparent_temperature',
 'weather_precipitation',
 'weather_rain',
 'weather_pressure_msl',
 'weather_surface_pressure',
 'weather_cloud_cover',
 'weather_cloud_cover_low',
 'weather_cloud_cover_mid',
 'weather_cloud_cover_high',
 'weather_et0_fao_evapotranspiration',
 'weather_vapour_pressure_deficit',
 'weather_soil_temperature_0_to_7cm',
 'weather_soil_moisture_0_to_7cm',
 'weather_sunshine_duration',
 'weather_is_day',
 'weather_direct_radiation',
 'precip_flag',
 'wind_dir_sin',
 'wind_dir_cos',
 'weather_code_cat_Clear',
 'weather_code_cat_Clouds',
 'weather_code_cat_Drizzle',
 'weather_code_cat_Rain',
 'weather_code_cat_null',
 'precipitation_lag_1h',
 'rain_lag_1h',
 'is_holiday_ar',
 'sin_hour',
 'cos_hour',
 'sin_dow',
 'cos_dow',
 'sin_month',
 'cos_month',
 'is_weekend',
 'payday_flag',
 'vacation_season',
 'peak_commute',
 'dep_last_DT_2',
 'dep_last_DT_3',
 'dep_last_DT_4',
 'dep_last_DT_5',
 'dep_last_DT_6',
 'dep_last_DT_7',
 'dep_last_DT_8',
 'dep_last_DT_9',
 'dep_last_DT_12',
 'dep_last_DT_13',
 'dep_last_DT_14',
 'dep_last_DT_17',
 'dep_last_DT_21',
 'dep_last_DT_22',
 'dep_last_DT_23',
 'dep_last_DT_24',
 'dep_last_DT_25',
 'dep_last_DT_26',
 'dep_last_DT_27',
 'dep_last_DT_29',
 'dep_last_DT_30',
 'dep_last_DT_31',
 'dep_last_DT_32',
 'dep_last_DT_33',
 'dep_last_DT_35',
 'dep_last_DT_36',
 'dep_last_DT_38',
 'dep_last_DT_41',
 'dep_last_DT_43',
 'dep_last_DT_44',
 'dep_last_DT_45',
 'dep_last_DT_46',
 'dep_last_DT_48',
 'dep_last_DT_49',
 'dep_last_DT_50',
 'dep_last_DT_51',
 'dep_last_DT_54',
 'dep_last_DT_56',
 'dep_last_DT_57',
 'dep_last_DT_58',
 'dep_last_DT_59',
 'dep_last_DT_60',
 'dep_last_DT_61',
 'dep_last_DT_63',
 'dep_last_DT_64',
 'dep_last_DT_65',
 'dep_last_DT_66',
 'dep_last_DT_68',
 'dep_last_DT_69',
 'dep_last_DT_70',
 'dep_last_DT_71',
 'dep_last_DT_73',
 'dep_last_DT_74',
 'dep_last_DT_75',
 'dep_last_DT_76',
 'dep_last_DT_77',
 'dep_last_DT_79',
 'dep_last_DT_80',
 'dep_last_DT_82',
 'dep_last_DT_83',
 'dep_last_DT_85',
 'dep_last_DT_86',
 'dep_last_DT_87',
 'dep_last_DT_89',
 'dep_last_DT_91',
 'dep_last_DT_92',
 'dep_last_DT_93',
 'dep_last_DT_94',
 'dep_last_DT_95',
 'dep_last_DT_96',
 'dep_last_DT_98',
 'dep_last_DT_99',
 'dep_last_DT_101',
 'dep_last_DT_102',
 'dep_last_DT_104',
 'dep_last_DT_107',
 'dep_last_DT_111',
 'dep_last_DT_112',
 'dep_last_DT_114',
 'dep_last_DT_116',
 'dep_last_DT_117',
 'dep_last_DT_118',
 'dep_last_DT_120',
 'dep_last_DT_121',
 'dep_last_DT_122',
 'dep_last_DT_124',
 'dep_last_DT_126',
 'dep_last_DT_128',
 'dep_last_DT_130',
 'dep_last_DT_131',
 'dep_last_DT_132',
 'dep_last_DT_134',
 'dep_last_DT_135',
 'dep_last_DT_137',
 'dep_last_DT_138',
 'dep_last_DT_144',
 'dep_last_DT_146',
 'dep_last_DT_148',
 'dep_last_DT_149',
 'dep_last_DT_150',
 'dep_last_DT_151',
 'dep_last_DT_152',
 'dep_last_DT_153',
 'dep_last_DT_155',
 'dep_last_DT_156',
 'dep_last_DT_158',
 'dep_last_DT_161',
 'dep_last_DT_162',
 'dep_last_DT_163',
 'dep_last_DT_164',
 'dep_last_DT_165',
 'dep_last_DT_166',
 'dep_last_DT_167',
 'dep_last_DT_168',
 'dep_last_DT_169',
 'dep_last_DT_171',
 'dep_last_DT_172',
 'dep_last_DT_174',
 'dep_last_DT_175',
 'dep_last_DT_176',
 'dep_last_DT_177',
 'dep_last_DT_179',
 'dep_last_DT_181',
 'dep_last_DT_182',
 'dep_last_DT_183',
 'dep_last_DT_184',
 'dep_last_DT_186',
 'dep_last_DT_187',
 'dep_last_DT_188',
 'dep_last_DT_189',
 'dep_last_DT_190',
 'dep_last_DT_191',
 'dep_last_DT_193',
 'dep_last_DT_194',
 'dep_last_DT_196',
 'dep_last_DT_197',
 'dep_last_DT_199',
 'dep_last_DT_200',
 'dep_last_DT_202',
 'dep_last_DT_203',
 'dep_last_DT_204',
 'dep_last_DT_205',
 'dep_last_DT_206',
 'dep_last_DT_207',
 'dep_last_DT_208',
 'dep_last_DT_210',
 'dep_last_DT_212',
 'dep_last_DT_213',
 'dep_last_DT_215',
 'dep_last_DT_216',
 'dep_last_DT_219',
 'dep_last_DT_220',
 'dep_last_DT_222',
 'dep_last_DT_223',
 'dep_last_DT_227',
 'dep_last_DT_228',
 'dep_last_DT_229',
 'dep_last_DT_230',
 'dep_last_DT_231',
 'dep_last_DT_232',
 'dep_last_DT_233',
 'dep_last_DT_234',
 'dep_last_DT_235',
 'dep_last_DT_236',
 'dep_last_DT_237',
 'dep_last_DT_239',
 'dep_last_DT_241',
 'dep_last_DT_242',
 'dep_last_DT_245',
 'dep_last_DT_247',
 'dep_last_DT_248',
 'dep_last_DT_251',
 'dep_last_DT_252',
 'dep_last_DT_253',
 'dep_last_DT_254',
 'dep_last_DT_255',
 'dep_last_DT_257',
 'dep_last_DT_258',
 'dep_last_DT_259',
 'dep_last_DT_260',
 'dep_last_DT_261',
 'dep_last_DT_262',
 'dep_last_DT_263',
 'dep_last_DT_264',
 'dep_last_DT_265',
 'dep_last_DT_267',
 'dep_last_DT_268',
 'dep_last_DT_269',
 'dep_last_DT_270',
 'dep_last_DT_271',
 'dep_last_DT_273',
 'dep_last_DT_275',
 'dep_last_DT_277',
 'dep_last_DT_278',
 'dep_last_DT_280',
 'dep_last_DT_281',
 'dep_last_DT_284',
 'dep_last_DT_289',
 'dep_last_DT_291',
 'dep_last_DT_299',
 'dep_last_DT_301',
 'dep_last_DT_302',
 'dep_last_DT_304',
 'dep_last_DT_307',
 'dep_last_DT_308',
 'dep_last_DT_309',
 'dep_last_DT_310',
 'dep_last_DT_311',
 'dep_last_DT_316',
 'dep_last_DT_318',
 'dep_last_DT_322',
 'dep_last_DT_323',
 'dep_last_DT_324',
 'dep_last_DT_327',
 'dep_last_DT_329',
 'dep_last_DT_330',
 'dep_last_DT_333',
 'dep_last_DT_335',
 'dep_last_DT_336',
 'dep_last_DT_340',
 'dep_last_DT_342',
 'dep_last_DT_348',
 'dep_last_DT_349',
 'dep_last_DT_353',
 'dep_last_DT_355',
 'dep_last_DT_358',
 'dep_last_DT_359',
 'dep_last_DT_361',
 'dep_last_DT_362',
 'dep_last_DT_363',
 'dep_last_DT_364',
 'dep_last_DT_366',
 'dep_last_DT_367',
 'dep_last_DT_368',
 'dep_last_DT_369',
 'dep_last_DT_370',
 'dep_last_DT_371',
 'dep_last_DT_372',
 'dep_last_DT_373',
 'dep_last_DT_374',
 'dep_last_DT_375',
 'dep_last_DT_376',
 'dep_last_DT_378',
 'dep_last_DT_379',
 'dep_last_DT_381',
 'dep_last_DT_382',
 'dep_last_DT_383',
 'dep_last_DT_384',
 'dep_last_DT_385',
 'dep_last_DT_386',
 'dep_last_DT_387',
 'dep_last_DT_392',
 'dep_last_DT_393',
 'dep_last_DT_395',
 'dep_last_DT_400',
 'dep_last_DT_403',
 'dep_last_DT_407',
 'dep_last_DT_408',
 'dep_last_DT_412',
 'dep_last_DT_413',
 'dep_last_DT_414',
 'dep_last_DT_416',
 'dep_last_DT_417',
 'dep_last_DT_418',
 'dep_last_DT_420',
 'dep_last_DT_422',
 'dep_last_DT_423',
 'dep_last_DT_424',
 'dep_last_DT_425',
 'dep_last_DT_426',
 'dep_last_DT_427',
 'dep_last_DT_428',
 'dep_last_DT_429',
 'dep_last_DT_431',
 'dep_last_DT_432',
 'dep_last_DT_433',
 'dep_last_DT_434',
 'dep_last_DT_435',
 'dep_last_DT_436',
 'dep_last_DT_440',
 'dep_last_DT_441',
 'dep_last_DT_443',
 'dep_last_DT_444',
 'dep_last_DT_448',
 'dep_last_DT_449',
 'dep_last_DT_453',
 'dep_last_DT_454',
 'dep_last_DT_455',
 'dep_last_DT_457',
 'dep_last_DT_458',
 'dep_last_DT_459',
 'dep_last_DT_460',
 'dep_last_DT_461',
 'dep_last_DT_464',
 'dep_last_DT_465',
 'dep_last_DT_466',
 'dep_last_DT_467',
 'dep_last_DT_468',
 'dep_last_DT_469',
 'dep_last_DT_471',
 'dep_last_DT_472',
 'dep_last_DT_473',
 'dep_last_DT_474',
 'dep_last_DT_475',
 'dep_last_DT_476',
 'dep_last_DT_477',
 'dep_last_DT_478',
 'dep_last_DT_479',
 'dep_last_DT_480',
 'dep_last_DT_481',
 'dep_last_DT_482',
 'dep_last_DT_483',
 'dep_last_DT_484',
 'dep_last_DT_485',
 'dep_last_DT_486',
 'dep_last_DT_487',
 'dep_last_DT_488',
 'dep_last_DT_489',
 'dep_last_DT_490',
 'dep_last_DT_491',
 'dep_last_DT_492',
 'dep_last_DT_493',
 'dep_last_DT_494',
 'dep_last_DT_496',
 'dep_last_DT_497',
 'dep_last_DT_498',
 'dep_last_DT_499',
 'dep_last_DT_500',
 'dep_last_DT_501',
 'dep_last_DT_502',
 'dep_last_DT_503',
 'dep_last_DT_504',
 'dep_last_DT_505',
 'dep_last_DT_506',
 'dep_last_DT_507',
 'dep_last_DT_508',
 'dep_last_DT_509',
 'dep_last_DT_511',
 'dep_last_DT_512',
 'dep_last_DT_513',
 'dep_last_DT_515',
 'dep_last_DT_516',
 'dep_last_DT_517',
 'dep_last_DT_518',
 'dep_last_DT_519',
 'dep_last_DT_520',
 'dep_last_DT_521',
 'dep_last_DT_522',
 'dep_last_DT_523',
 'dep_last_DT_524',
 'dep_last_DT_525',
 'dep_last_DT_526',
 'dep_last_DT_527',
 'dep_last_DT_528',
 'dep_last_DT_529',
 'dep_last_DT_530',
 'dep_last_DT_531',
 'dep_last_DT_532',
 'dep_last_DT_533',
 'dep_last_DT_534',
 'dep_last_DT_535',
 'dep_last_DT_536',
 'dep_last_DT_537',
 'dep_last_DT_538',
 'dep_last_DT_539',
 'dep_last_DT_540',
 'dep_last_DT_541',
 'dep_last_DT_542',
 'dep_last_DT_543',
 'dep_last_DT_544',
 'dep_last_DT_545',
 'dep_last_DT_546',
 'dep_last_DT_547',
 'dep_last_DT_548',
 'dep_last_DT_549',
 'dep_last_DT_550',
 'dep_last_DT_551',
 'dep_last_DT_552',
 'dep_last_DT_553',
 'dep_last_DT_554',
 'dep_last_DT_556',
 'trip_dur_mean_last_DT_2',
 'trip_dur_mean_last_DT_3',
 'trip_dur_mean_last_DT_4',
 'trip_dur_mean_last_DT_5',
 'trip_dur_mean_last_DT_6',
 'trip_dur_mean_last_DT_7',
 'trip_dur_mean_last_DT_8',
 'trip_dur_mean_last_DT_9',
 'trip_dur_mean_last_DT_12',
 'trip_dur_mean_last_DT_13',
 'trip_dur_mean_last_DT_14',
 'trip_dur_mean_last_DT_17',
 'trip_dur_mean_last_DT_21',
 'trip_dur_mean_last_DT_22',
 'trip_dur_mean_last_DT_23',
 'trip_dur_mean_last_DT_24',
 'trip_dur_mean_last_DT_25',
 'trip_dur_mean_last_DT_26',
 'trip_dur_mean_last_DT_27',
 'trip_dur_mean_last_DT_29',
 'trip_dur_mean_last_DT_30',
 'trip_dur_mean_last_DT_31',
 'trip_dur_mean_last_DT_32',
 'trip_dur_mean_last_DT_33',
 'trip_dur_mean_last_DT_35',
 'trip_dur_mean_last_DT_36',
 'trip_dur_mean_last_DT_38',
 'trip_dur_mean_last_DT_41',
 'trip_dur_mean_last_DT_43',
 'trip_dur_mean_last_DT_44',
 'trip_dur_mean_last_DT_45',
 'trip_dur_mean_last_DT_46',
 'trip_dur_mean_last_DT_48',
 'trip_dur_mean_last_DT_49',
 'trip_dur_mean_last_DT_50',
 'trip_dur_mean_last_DT_51',
 'trip_dur_mean_last_DT_54',
 'trip_dur_mean_last_DT_56',
 'trip_dur_mean_last_DT_57',
 'trip_dur_mean_last_DT_58',
 'trip_dur_mean_last_DT_59',
 'trip_dur_mean_last_DT_60',
 'trip_dur_mean_last_DT_61',
 'trip_dur_mean_last_DT_63',
 'trip_dur_mean_last_DT_64',
 'trip_dur_mean_last_DT_65',
 'trip_dur_mean_last_DT_66',
 'trip_dur_mean_last_DT_68',
 'trip_dur_mean_last_DT_69',
 'trip_dur_mean_last_DT_70',
 'trip_dur_mean_last_DT_71',
 'trip_dur_mean_last_DT_73',
 'trip_dur_mean_last_DT_74',
 'trip_dur_mean_last_DT_75',
 'trip_dur_mean_last_DT_76',
 'trip_dur_mean_last_DT_77',
 'trip_dur_mean_last_DT_79',
 'trip_dur_mean_last_DT_80',
 'trip_dur_mean_last_DT_82',
 'trip_dur_mean_last_DT_83',
 'trip_dur_mean_last_DT_85',
 'trip_dur_mean_last_DT_86',
 'trip_dur_mean_last_DT_87',
 'trip_dur_mean_last_DT_89',
 'trip_dur_mean_last_DT_91',
 'trip_dur_mean_last_DT_92',
 'trip_dur_mean_last_DT_93',
 'trip_dur_mean_last_DT_94',
 'trip_dur_mean_last_DT_95',
 'trip_dur_mean_last_DT_96',
 'trip_dur_mean_last_DT_98',
 'trip_dur_mean_last_DT_99',
 'trip_dur_mean_last_DT_101',
 'trip_dur_mean_last_DT_102',
 'trip_dur_mean_last_DT_104',
 'trip_dur_mean_last_DT_107',
 'trip_dur_mean_last_DT_111',
 'trip_dur_mean_last_DT_112',
 'trip_dur_mean_last_DT_114',
 'trip_dur_mean_last_DT_116',
 'trip_dur_mean_last_DT_117',
 'trip_dur_mean_last_DT_118',
 'trip_dur_mean_last_DT_120',
 'trip_dur_mean_last_DT_121',
 'trip_dur_mean_last_DT_122',
 'trip_dur_mean_last_DT_124',
 'trip_dur_mean_last_DT_126',
 'trip_dur_mean_last_DT_128',
 'trip_dur_mean_last_DT_130',
 'trip_dur_mean_last_DT_131',
 'trip_dur_mean_last_DT_132',
 'trip_dur_mean_last_DT_134',
 'trip_dur_mean_last_DT_135',
 'trip_dur_mean_last_DT_137',
 'trip_dur_mean_last_DT_138',
 'trip_dur_mean_last_DT_144',
 'trip_dur_mean_last_DT_146',
 'trip_dur_mean_last_DT_148',
 'trip_dur_mean_last_DT_149',
 'trip_dur_mean_last_DT_150',
 'trip_dur_mean_last_DT_151',
 'trip_dur_mean_last_DT_152',
 'trip_dur_mean_last_DT_153',
 'trip_dur_mean_last_DT_155',
 'trip_dur_mean_last_DT_156',
 'trip_dur_mean_last_DT_158',
 'trip_dur_mean_last_DT_161',
 'trip_dur_mean_last_DT_162',
 'trip_dur_mean_last_DT_163',
 'trip_dur_mean_last_DT_164',
 'trip_dur_mean_last_DT_165',
 'trip_dur_mean_last_DT_166',
 'trip_dur_mean_last_DT_167',
 'trip_dur_mean_last_DT_168',
 'trip_dur_mean_last_DT_169',
 'trip_dur_mean_last_DT_171',
 'trip_dur_mean_last_DT_172',
 'trip_dur_mean_last_DT_174',
 'trip_dur_mean_last_DT_175',
 'trip_dur_mean_last_DT_176',
 'trip_dur_mean_last_DT_177',
 'trip_dur_mean_last_DT_179',
 'trip_dur_mean_last_DT_181',
 'trip_dur_mean_last_DT_182',
 'trip_dur_mean_last_DT_183',
 'trip_dur_mean_last_DT_184',
 'trip_dur_mean_last_DT_186',
 'trip_dur_mean_last_DT_187',
 'trip_dur_mean_last_DT_188',
 'trip_dur_mean_last_DT_189',
 'trip_dur_mean_last_DT_190',
 'trip_dur_mean_last_DT_191',
 'trip_dur_mean_last_DT_193',
 'trip_dur_mean_last_DT_194',
 'trip_dur_mean_last_DT_196',
 'trip_dur_mean_last_DT_197',
 'trip_dur_mean_last_DT_199',
 'trip_dur_mean_last_DT_200',
 'trip_dur_mean_last_DT_202',
 'trip_dur_mean_last_DT_203',
 'trip_dur_mean_last_DT_204',
 'trip_dur_mean_last_DT_205',
 'trip_dur_mean_last_DT_206',
 'trip_dur_mean_last_DT_207',
 'trip_dur_mean_last_DT_208',
 'trip_dur_mean_last_DT_210',
 'trip_dur_mean_last_DT_212',
 'trip_dur_mean_last_DT_213',
 'trip_dur_mean_last_DT_215',
 'trip_dur_mean_last_DT_216',
 'trip_dur_mean_last_DT_219',
 'trip_dur_mean_last_DT_220',
 'trip_dur_mean_last_DT_222',
 'trip_dur_mean_last_DT_223',
 'trip_dur_mean_last_DT_227',
 'trip_dur_mean_last_DT_228',
 'trip_dur_mean_last_DT_229',
 'trip_dur_mean_last_DT_230',
 'trip_dur_mean_last_DT_231',
 'trip_dur_mean_last_DT_232',
 'trip_dur_mean_last_DT_233',
 'trip_dur_mean_last_DT_234',
 'trip_dur_mean_last_DT_235',
 'trip_dur_mean_last_DT_236',
 'trip_dur_mean_last_DT_237',
 'trip_dur_mean_last_DT_239',
 'trip_dur_mean_last_DT_241',
 'trip_dur_mean_last_DT_242',
 'trip_dur_mean_last_DT_245',
 'trip_dur_mean_last_DT_247',
 'trip_dur_mean_last_DT_248',
 'trip_dur_mean_last_DT_251',
 'trip_dur_mean_last_DT_252',
 'trip_dur_mean_last_DT_253',
 'trip_dur_mean_last_DT_254',
 'trip_dur_mean_last_DT_255',
 'trip_dur_mean_last_DT_257',
 'trip_dur_mean_last_DT_258',
 'trip_dur_mean_last_DT_259',
 'trip_dur_mean_last_DT_260',
 'trip_dur_mean_last_DT_261',
 'trip_dur_mean_last_DT_262',
 'trip_dur_mean_last_DT_263',
 'trip_dur_mean_last_DT_264',
 'trip_dur_mean_last_DT_265',
 'trip_dur_mean_last_DT_267',
 'trip_dur_mean_last_DT_268',
 'trip_dur_mean_last_DT_269',
 'trip_dur_mean_last_DT_270',
 'trip_dur_mean_last_DT_271',
 'trip_dur_mean_last_DT_273',
 'trip_dur_mean_last_DT_275',
 'trip_dur_mean_last_DT_277',
 'trip_dur_mean_last_DT_278',
 'trip_dur_mean_last_DT_280',
 'trip_dur_mean_last_DT_281',
 'trip_dur_mean_last_DT_284',
 'trip_dur_mean_last_DT_289',
 'trip_dur_mean_last_DT_291',
 'trip_dur_mean_last_DT_299',
 'trip_dur_mean_last_DT_301',
 'trip_dur_mean_last_DT_302',
 'trip_dur_mean_last_DT_304',
 'trip_dur_mean_last_DT_307',
 'trip_dur_mean_last_DT_308',
 'trip_dur_mean_last_DT_309',
 'trip_dur_mean_last_DT_310',
 'trip_dur_mean_last_DT_311',
 'trip_dur_mean_last_DT_316',
 'trip_dur_mean_last_DT_318',
 'trip_dur_mean_last_DT_322',
 'trip_dur_mean_last_DT_323',
 'trip_dur_mean_last_DT_324',
 'trip_dur_mean_last_DT_327',
 'trip_dur_mean_last_DT_329',
 'trip_dur_mean_last_DT_330',
 'trip_dur_mean_last_DT_333',
 'trip_dur_mean_last_DT_335',
 'trip_dur_mean_last_DT_336',
 'trip_dur_mean_last_DT_340',
 'trip_dur_mean_last_DT_342',
 'trip_dur_mean_last_DT_348',
 'trip_dur_mean_last_DT_349',
 'trip_dur_mean_last_DT_353',
 'trip_dur_mean_last_DT_355',
 'trip_dur_mean_last_DT_358',
 'trip_dur_mean_last_DT_359',
 'trip_dur_mean_last_DT_361',
 'trip_dur_mean_last_DT_362',
 'trip_dur_mean_last_DT_363',
 'trip_dur_mean_last_DT_364',
 'trip_dur_mean_last_DT_366',
 'trip_dur_mean_last_DT_367',
 'trip_dur_mean_last_DT_368',
 'trip_dur_mean_last_DT_369',
 'trip_dur_mean_last_DT_370',
 'trip_dur_mean_last_DT_371',
 'trip_dur_mean_last_DT_372',
 'trip_dur_mean_last_DT_373',
 'trip_dur_mean_last_DT_374',
 'trip_dur_mean_last_DT_375',
 'trip_dur_mean_last_DT_376',
 'trip_dur_mean_last_DT_378',
 'trip_dur_mean_last_DT_379',
 'trip_dur_mean_last_DT_381',
 'trip_dur_mean_last_DT_382',
 'trip_dur_mean_last_DT_383',
 'trip_dur_mean_last_DT_384',
 'trip_dur_mean_last_DT_385',
 'trip_dur_mean_last_DT_386',
 'trip_dur_mean_last_DT_387',
 'trip_dur_mean_last_DT_392',
 'trip_dur_mean_last_DT_393',
 'trip_dur_mean_last_DT_395',
 'trip_dur_mean_last_DT_400',
 'trip_dur_mean_last_DT_403',
 'trip_dur_mean_last_DT_407',
 'trip_dur_mean_last_DT_408',
 'trip_dur_mean_last_DT_412',
 'trip_dur_mean_last_DT_413',
 'trip_dur_mean_last_DT_414',
 'trip_dur_mean_last_DT_416',
 'trip_dur_mean_last_DT_417',
 'trip_dur_mean_last_DT_418',
 'trip_dur_mean_last_DT_420',
 'trip_dur_mean_last_DT_422',
 'trip_dur_mean_last_DT_423',
 'trip_dur_mean_last_DT_424',
 'trip_dur_mean_last_DT_425',
 'trip_dur_mean_last_DT_426',
 'trip_dur_mean_last_DT_427',
 'trip_dur_mean_last_DT_428',
 'trip_dur_mean_last_DT_429',
 'trip_dur_mean_last_DT_431',
 'trip_dur_mean_last_DT_432',
 'trip_dur_mean_last_DT_433',
 'trip_dur_mean_last_DT_434',
 'trip_dur_mean_last_DT_435',
 'trip_dur_mean_last_DT_436',
 'trip_dur_mean_last_DT_440',
 'trip_dur_mean_last_DT_441',
 'trip_dur_mean_last_DT_443',
 'trip_dur_mean_last_DT_444',
 'trip_dur_mean_last_DT_448',
 'trip_dur_mean_last_DT_449',
 'trip_dur_mean_last_DT_453',
 'trip_dur_mean_last_DT_454',
 'trip_dur_mean_last_DT_455',
 'trip_dur_mean_last_DT_457',
 'trip_dur_mean_last_DT_458',
 'trip_dur_mean_last_DT_459',
 'trip_dur_mean_last_DT_460',
 'trip_dur_mean_last_DT_461',
 'trip_dur_mean_last_DT_464',
 'trip_dur_mean_last_DT_465',
 'trip_dur_mean_last_DT_466',
 'trip_dur_mean_last_DT_467',
 'trip_dur_mean_last_DT_468',
 'trip_dur_mean_last_DT_469',
 'trip_dur_mean_last_DT_471',
 'trip_dur_mean_last_DT_472',
 'trip_dur_mean_last_DT_473',
 'trip_dur_mean_last_DT_474',
 'trip_dur_mean_last_DT_475',
 'trip_dur_mean_last_DT_476',
 'trip_dur_mean_last_DT_477',
 'trip_dur_mean_last_DT_478',
 'trip_dur_mean_last_DT_479',
 'trip_dur_mean_last_DT_480',
 'trip_dur_mean_last_DT_481',
 'trip_dur_mean_last_DT_482',
 'trip_dur_mean_last_DT_483',
 'trip_dur_mean_last_DT_484',
 'trip_dur_mean_last_DT_485',
 'trip_dur_mean_last_DT_486',
 'trip_dur_mean_last_DT_487',
 'trip_dur_mean_last_DT_488',
 'trip_dur_mean_last_DT_489',
 'trip_dur_mean_last_DT_490',
 'trip_dur_mean_last_DT_491',
 'trip_dur_mean_last_DT_492',
 'trip_dur_mean_last_DT_493',
 'trip_dur_mean_last_DT_494',
 'trip_dur_mean_last_DT_496',
 'trip_dur_mean_last_DT_497',
 'trip_dur_mean_last_DT_498',
 'trip_dur_mean_last_DT_499',
 'trip_dur_mean_last_DT_500',
 'trip_dur_mean_last_DT_501',
 'trip_dur_mean_last_DT_502',
 'trip_dur_mean_last_DT_503',
 'trip_dur_mean_last_DT_504',
 'trip_dur_mean_last_DT_505',
 'trip_dur_mean_last_DT_506',
 'trip_dur_mean_last_DT_507',
 'trip_dur_mean_last_DT_508',
 'trip_dur_mean_last_DT_509',
 'trip_dur_mean_last_DT_511',
 'trip_dur_mean_last_DT_512',
 'trip_dur_mean_last_DT_513',
 'trip_dur_mean_last_DT_515',
 'trip_dur_mean_last_DT_516',
 'trip_dur_mean_last_DT_517',
 'trip_dur_mean_last_DT_518',
 'trip_dur_mean_last_DT_519',
 'trip_dur_mean_last_DT_520',
 'trip_dur_mean_last_DT_521',
 'trip_dur_mean_last_DT_522',
 'trip_dur_mean_last_DT_523',
 'trip_dur_mean_last_DT_524',
 'trip_dur_mean_last_DT_525',
 'trip_dur_mean_last_DT_526',
 'trip_dur_mean_last_DT_527',
 'trip_dur_mean_last_DT_528',
 'trip_dur_mean_last_DT_529',
 'trip_dur_mean_last_DT_530',
 'trip_dur_mean_last_DT_531',
 'trip_dur_mean_last_DT_532',
 'trip_dur_mean_last_DT_533',
 'trip_dur_mean_last_DT_534',
 'trip_dur_mean_last_DT_535',
 'trip_dur_mean_last_DT_536',
 'trip_dur_mean_last_DT_537',
 'trip_dur_mean_last_DT_538',
 'trip_dur_mean_last_DT_539',
 'trip_dur_mean_last_DT_540',
 'trip_dur_mean_last_DT_541',
 'trip_dur_mean_last_DT_542',
 'trip_dur_mean_last_DT_543',
 'trip_dur_mean_last_DT_544',
 'trip_dur_mean_last_DT_545',
 'trip_dur_mean_last_DT_546',
 'trip_dur_mean_last_DT_547',
 'trip_dur_mean_last_DT_548',
 'trip_dur_mean_last_DT_549',
 'trip_dur_mean_last_DT_550',
 'trip_dur_mean_last_DT_551',
 'trip_dur_mean_last_DT_552',
 'trip_dur_mean_last_DT_553',
 'trip_dur_mean_last_DT_554',
 'trip_dur_mean_last_DT_556',
 'model_FIT_cnt_2',
 'model_FIT_cnt_3',
 'model_FIT_cnt_4',
 'model_FIT_cnt_5',
 'model_FIT_cnt_6',
 'model_FIT_cnt_7',
 'model_FIT_cnt_8',

In [4]:
y_wide = pl.read_parquet(r"C:\Users\xxx\Documents\GitHub\EcoBici-AI\notebooks\feature_checkpoints\y_wide.parquet")

In [5]:
y_wide.shape

(29183, 382)

In [18]:
import polars as pl

def check_nans(df: pl.DataFrame, name: str = "df") -> None:
    # Handle datetime columns separately from numeric columns
    datetime_cols = df.select(pl.col(pl.Datetime)).columns
    numeric_cols = [col for col in df.columns if col not in datetime_cols]
    
    # Get NaN counts for numeric columns
    per_col_numeric = (df.select([pl.col(col).is_nan().sum() for col in numeric_cols])
                      .row(0) if numeric_cols else [])
    
    # Get null counts for datetime columns 
    per_col_datetime = (df.select([pl.col(col).is_null().sum() for col in datetime_cols])
                       .row(0) if datetime_cols else [])
    
    # Combine results
    per_col = list(per_col_numeric) + list(per_col_datetime)
    total_nans = sum(per_col)

    if total_nans == 0:
        print(f"✅ {name}: no NaN/null values found.")
    else:
        print(f"⚠️  {name}: {total_nans:,} NaN/null values detected.")
        # Create DataFrame of columns with NaNs
        nan_cols = pl.DataFrame({
            "column": df.columns,
            "nans": per_col
        })
        (nan_cols
         .filter(pl.col("nans") > 0)
         .sort("nans", descending=True)
         .show())

# ------------------------------------------------------------------
check_nans(X_wide, "X_wide") 
check_nans(y_wide, "y_wide")

✅ X_wide: no NaN/null values found.
✅ y_wide: no NaN/null values found.